from api.routes import (
    news_article, hum_int, cyb_int, open_source_int, social_media,
    informant, person_of_interest, intel_document, intel_investigation_file,
    general_intel, in_sum, intel,
    mas_int, med_int, tech_int, sig_int, geo_int, im_int,
    financial_int, counter_int, sit_rep,
    human_source, operator_intel, gov_source, report_data,
    intelligence_officer, intelligence_analyst, intelligence_collector,
    ci_agent, all_source_analyst,
    intel_case, photos,
)

all_routers = [
    news_article.router,
    hum_int.router,
    cyb_int.router,
    open_source_int.router,
    social_media.router,
    informant.router,
    person_of_interest.router,
    intel_document.router,
    intel_investigation_file.router,
    general_intel.router,
    in_sum.router,
    intel.router,
    mas_int.router,
    med_int.router,
    tech_int.router,
    sig_int.router,
    geo_int.router,
    im_int.router,
    financial_int.router,
    counter_int.router,
    sit_rep.router,
    human_source.router,
    operator_intel.router,
    gov_source.router,
    report_data.router,
    intelligence_officer.router,
    intelligence_analyst.router,
    intelligence_collector.router,
    ci_agent.router,
    all_source_analyst.router,
    intel_case.router,
    photos.router,
]
